name: Build the new Desktop Client (Electron)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Use Node.js 18.x
          uses: actions/setup-node@v3
          with:
            node-version: 18.x
            cache: 'npm'
            cache-dependency-path: desktop/package-lock.json
        - run: cd desktop && npm ci
        - run: cd desktop && npm run build --if-present
        - run: cd desktop && npm run test:nowatch
          
