name: Build the new Desktop Client (Electron)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Use Node.js 18.x
          uses: actions/setup-node@v3
          with:
            node-version: 18.x
            cache: 'npm'
            working-directory: ./desktop
        - run: |
            npm ci
            npm run build --if-present
            npm run test:nowatch
          
